--yes

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -30,7 +30,7 @@ fi
 # Handle env update
 if [[ "$(plugin_read_config UPDATE "true")" == "true" ]]; then
   echo "Auto-Update environment $CONDA_ENV."
-  conda update -n "${CONDA_ENV}" --file "${CONDA_ENV_FILE}"
+  conda update -y -n "${CONDA_ENV}" --file "${CONDA_ENV_FILE}"
 fi
 
 
@@ -38,7 +38,7 @@ if conda activate "$CONDA_ENV"; then
   :
 else
   echo "Creating environment $CONDA_ENV from $CONDA_ENV_FILE."
-  conda create -n "$CONDA_ENV" --file "$CONDA_ENV_FILE" || { echo "Failed to create environment."; exit 1; }
+  conda create -y -n "$CONDA_ENV" --file "$CONDA_ENV_FILE" || { echo "Failed to create environment."; exit 1; }
   conda activate "$CONDA_ENV" || { echo "Failed to activate new environment."; exit 1; }
 fi
 
