Handle missing environment config

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -23,12 +23,14 @@ fi
 CONDA_ENV="${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_BRANCH//:/_}"
 CONDA_ARGS=""
 
-if [ -e "$(plugin_read_config ENVIRONMENT)" ]; then
-  CONDA_ENV_FILE=${BUILDKITE_PLUGIN_CONDA_ENVIRONMENT}
-  CONDA_ARGS+="--file ${CONDA_ENV_FILE}"
-elif [ -n "${BUILDKITE_PLUGIN_CONDA_ENVIRONMENT}" ]; then
-  echo "Environment definition file not found: ${BUILDKITE_PLUGIN_CONDA_ENVIRONMENT}"
-  exit 1
+if [ -n "$(plugin_read_config ENVIRONMENT)" ]; then
+  if [ -e "$(plugin_read_config ENVIRONMENT)" ]; then
+    CONDA_ENV_FILE=${BUILDKITE_PLUGIN_CONDA_ENVIRONMENT}
+    CONDA_ARGS+="--file ${CONDA_ENV_FILE}"
+  else
+    echo "Environment definition file not found: ${BUILDKITE_PLUGIN_CONDA_ENVIRONMENT}"
+    exit 1
+  fi
 fi
 
 if [ -n "$(plugin_read_config PACKAGES)" ]; then
